/**
 * The Stolen Lands map sheets and their measured hex geometry.
 *
 * GENERATED by scripts/extract-kingdom-assets.py. The same data is served as
 * public/kingdom/map/manifest.json; this module exists so the client gets it
 * typed and bundled instead of fetching it. Re-run the script rather than
 * editing the numbers by hand.
 */

import type { HexGeometry } from "./hex";

export interface MapSheet {
  /** 1-based sheet number, matching Hex.sheet in the database. */
  id: number;
  name: string;
  file: string;
  width: number;
  height: number;
  hex: HexGeometry;
}

export const MAP_SHEETS: MapSheet[] = [
  {
    id: 1,
    name: "Sheet 1",
    file: "/kingdom/map/sheet-1.jpg",
    width: 1261,
    height: 1636,
    hex: {
      colPitch: 175,
      rowPitch: 152,
      originX: 80,
      originY: 55,
      cols: 7,
      rows: 11,
    },
  },
  {
    id: 2,
    name: "Sheet 2",
    file: "/kingdom/map/sheet-2.jpg",
    width: 1261,
    height: 1636,
    hex: {
      colPitch: 175,
      rowPitch: 152,
      originX: 67,
      originY: 60,
      cols: 7,
      rows: 11,
    },
  },
  {
    id: 3,
    name: "Sheet 3",
    file: "/kingdom/map/sheet-3.jpg",
    width: 1262,
    height: 1636,
    hex: {
      colPitch: 175,
      rowPitch: 152,
      originX: 98,
      originY: 64,
      cols: 7,
      rows: 11,
    },
  },
  {
    id: 4,
    name: "Sheet 4",
    file: "/kingdom/map/sheet-4.jpg",
    width: 1261,
    height: 1636,
    hex: {
      colPitch: 175,
      rowPitch: 152,
      originX: 76,
      originY: 59,
      cols: 7,
      rows: 11,
    },
  },
];

export function getMapSheet(id: number): MapSheet | undefined {
  return MAP_SHEETS.find((s) => s.id === id);
}
