/**
 * Kingdom activity catalog - the verb layer of the Kingdom subsystem.
 *
 * GENERATED by scripts/extract-kingdom-activities.py from the Kingmaker
 * Player's Guide, with the Vance & Kerenshara changes applied on top: Take
 * Charge and Reconnoiter Hex are added, and Capital Investment and Request
 * Foreign Aid are amended. Re-run the script rather than editing the data
 * below by hand.
 */

import type { ProficiencyRank } from "./kingdom";

/** Which step of the Kingdom turn an activity belongs to. */
export type ActivityPhase =
  | "leadership"
  | "region"
  | "civic"
  | "commerce"
  | "army";

export const ACTIVITY_PHASE_LABELS: Record<ActivityPhase, string> = {
  leadership: "Leadership",
  region: "Region",
  civic: "Civic",
  commerce: "Commerce",
  army: "Army",
};

export interface ActivitySkillOption {
  skill: string;
  /** Lowest proficiency rank that unlocks this skill for the activity. */
  minRank: ProficiencyRank;
}

export interface ActivityOutcomes {
  criticalSuccess?: string;
  success?: string;
  failure?: string;
  criticalFailure?: string;
}

export interface KingdomActivityDef {
  id: string;
  name: string;
  phase: ActivityPhase;
  /** Skills that can attempt this. Empty when the player picks any skill. */
  skills: ActivitySkillOption[];
  traits: string[];
  requirements: string | null;
  description: string;
  outcomes: ActivityOutcomes;
  /**
   * Where the skill comes from when `skills` is empty. "any" lets the player
   * pick a Kingdom skill, "structure" takes it from the structure being built,
   * "varies" from a table the activity points at, and "none" means the
   * activity resolves without a check.
   */
  skillChoice?: "any" | "structure" | "varies" | "none";
  /** Lowest rank that qualifies when `skillChoice` is "any". */
  anyMinRank?: ProficiencyRank;
  /** Set when the activity exists only under the V&K house rules. */
  source?: "VK";
  /** A V&K amendment to an otherwise RAW activity. */
  vkNote?: string;
}

export const KINGDOM_ACTIVITIES: KingdomActivityDef[] = [
  {
    id: "abandon-hex",
    name: "Abandon Hex",
    phase: "region",
    skills: [{ skill: "exploration", minRank: 0 }, { skill: "wilderness", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "The hex to be abandoned must be controlled.",
    description: "After careful consideration, you decide that you would rather not hold onto a particular hex as part of your claimed territory. You renounce your claim to it and pull back any settlers or explorers. Attempt a basic Exploration or Wilderness check. You can abandon more than one hex at a time, but each additional hex you abandon increases the DC of this check by 1.",
    outcomes: { criticalSuccess: "You abandon the hex or hexes, decreasing your kingdom's Size by 1 per hex abandoned (this affects all statistics determined by Size; see page 38). Settlers and explorers return and resettle elsewhere in your kingdom, bringing with them bits of salvage from the abandoned hexes. Gain 1 RP per abandoned hex.", success: "As critical success, but you gain no RP and increase Unrest by 1.", failure: "You abandon the hex or hexes, decreasing your kingdom's Size by 1 per hex abandoned (this affects all statistics determined by Size; see page 38). Some citizens become disgruntled refugees who refuse to leave the hex. Increase Unrest by 2 and then attempt a DC 6 flat check. If you fail, the refugees become bandits, and during your next Event phase, your kingdom experiences a Squatters kingdom event automatically in addition to any other event that might occur.", criticalFailure: "As failure, but increase Unrest by 3 and automatically experience a Bandit Activity kingdom event instead of a Squatters event." },
  },
  {
    id: "build-roads",
    name: "Build Roads",
    phase: "region",
    skills: [{ skill: "engineering", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "The hex in which you seek to build roads must be claimed by your kingdom.",
    description: "You order your kingdom's engineers to construct a network of robust roads through the hex. Travel along roads uses a terrain type one step better than the surrounding terrain; for example, roads through forest hexes—normally difficult terrain—allow travel as if it were open terrain. Spend RP as determined by the hex's most inhospitable terrain (see Building on Rough Terrain on page 23; if the hex includes any rivers that cross the hex from one hex side to any other, you must spend double the normal RP cost to also build bridges; this adds the Bridge structure to that hex). Then attempt a basic check. Work with the GM to determine where your roads appear on the map.",
    outcomes: { criticalSuccess: "You build roads into the target hex and one adjacent claimed hex that doesn't yet have roads and whose terrain features are at least as hospitable as those of the target hex. If no adjacent hex is appropriate, treat this result as a Success instead.", success: "You build roads in the hex.", failure: "You fail to build roads in the hex.", criticalFailure: "Your attempt to build roads ends in disaster. Not only do you fail to build roads, but you lose several workers to an accident, banditry, a vicious monster, or some other unforeseen occurrence. Gain 1 Unrest." },
  },
  {
    id: "build-structure",
    name: "Build Structure",
    phase: "civic",
    skills: [],
    traits: ["CIVIC", "DOWNTIME"],
    requirements: null,
    description: "You attempt to build a structure in the settlement that's granting the Civic activity. You may choose any structure for which you meet the requirements. Select the appropriate number of contiguous buildable lots in a single block as specified by the structure's entry and spend the specified RP and Commodity cost. Then attempt the structure's skill check. You can also use this activity to attempt to repair a structure that was damaged as the result of an event but hasn't been replaced by Rubble. To do this, first spend half the structure's listed RP and Commodity cost, and then attempt the specified check. The existing structure gives you a +2 item bonus to the check. On a success, record the new construction on the Urban Grid. Unless the structure's entry states otherwise, its effects are immediate; if the structure adjusts a Ruin's point total, adjust it upon construction.",
    outcomes: { criticalSuccess: "You construct or repair the structure with great efficiency and get back half of the Commodities spent in construction or repair.", success: "You construct or repair the structure.", failure: "You fail to construct or repair the structure. You can try to complete it next Kingdom turn; if you do so, you do not need to re-pay the RP and Commodity cost.", criticalFailure: "You fail to construct the structure; if you were attempting to repair a damaged structure, it is reduced to Rubble. In either event, Rubble now fills the structure's lots, which must be cleared with the Demolish activity before you can attempt to Build a Structure in them again." },
    skillChoice: "structure",
  },
  {
    id: "capital-investment",
    name: "Capital Investment",
    phase: "leadership",
    skills: [{ skill: "trade", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: "You must be in the Capital or within the influence of a settlement that contains at least one Bank.",
    description: "You contribute funds from your personal wealth for the good of the kingdom, including coinage, gems, jewelry, weapons and armor salvaged from enemies, magical or alchemical items, and so on. Your contribution generates economic activity in the form of RP that can be used during your current Kingdom turn or on the next Kingdom turn (your choice). You can use Capital Investment to repay funds from Tap Treasury (page 33). In this case, no roll is needed and you simply deduct the appropriate amount of funds from your personal wealth to pay back that which was borrowed. When you use Capital Investment to generate RP, the amount of gp required to make an investment is set by your kingdom's level. Investments below this amount cause your attempt to suffer an automatic critical failure, while investments above this amount are lost. The investment required is equal to the value listed on Table 10-9: Party Treasure by Level in the Pathfinder Core Rulebook (page 509); use the value for your kingdom's level under Currency per Additional PC as the required investment value. This is a basic check.",
    outcomes: { criticalSuccess: "Your kingdom reaps the benefits of your investment. Immediately roll 4 Resource Dice. Gain RP equal to the result.", success: "Your investment helps the economy. Immediately roll 2 Resource Dice. Gain RP equal to the result.", failure: "Your investment ends up being used to shore up shortfalls elsewhere. Gain 1d4 RP.", criticalFailure: "Your investment is embezzled, lost, or otherwise misappropriated. Choose one of the following: either roll 1 Resource Die and gain RP equal to the result and also increase your Crime by an equal amount, or gain 0 RP and increase Crime by 1." },
  },
  {
    id: "celebrate-holiday",
    name: "Celebrate Holiday",
    phase: "leadership",
    skills: [{ skill: "folklore", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You declare a day of celebration. Holidays may be religious, historical, martial, or simply festive, but all relieve your citizens from their labors and give them a chance to make merry at the kingdom's expense. Attempt a basic check, but if your kingdom Celebrated a Holiday the previous turn, the DC increases by 4, as your kingdom hasn't had a chance to recover from the previous gala.",
    outcomes: { criticalSuccess: "Your holidays are a delight to your people. The event is expensive, but incidental income from the celebrants covers the cost. You gain a +2 circumstance bonus to Loyalty-based checks until the end of your next Kingdom turn.", success: "Your holidays are a success, but they're also expensive. You gain a +1 circumstance bonus to Loyalty-based checks until the end of your next Kingdom turn. Immediately roll 1 Resource Die and spend RP equal to the result. If you can't afford this cost, treat this result as a Critical Failure instead.", failure: "The holiday passes with little enthusiasm, but is still expensive. Immediately roll 1 Resource Die and spend RP equal to the result. If you can't afford this cost, treat this result as a Critical Failure instead.", criticalFailure: "Your festival days are poorly organized, and the citizens actively mock your failed attempt to celebrate. During the next turn, reduce your Resource Dice total by 4. The failure also causes you to take a -1 circumstance penalty to Loyalty-based checks until the end of the next Kingdom turn." },
  },
  {
    id: "claim-hex",
    name: "Claim Hex",
    phase: "region",
    skills: [{ skill: "exploration", minRank: 0 }, { skill: "intrigue", minRank: 0 }, { skill: "magic", minRank: 0 }, { skill: "wilderness", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "You have Reconnoitered the hex to be claimed during hexploration. This hex must be adjacent to at least one hex that's already part of your kingdom. If the hex to be claimed contains dangerous hazards or monsters, they must first be cleared out—either via standard adventuring or the Clear Hex activity.",
    description: "Your surveyors fully explore the hex and attempt to add it into your kingdom's domain. Spend 1 RP and then attempt a basic Exploration, Intrigue, Magic, or Wilderness check.",
    outcomes: { criticalSuccess: "You claim the hex and immediately add it to your territory, increasing your kingdom's Size by 1 (this affects all statistics determined by Size; see page 38). Your occupation of the hex goes so smoothly that you can immediately attempt another Region activity.", success: "You claim the hex and add it to your territory, increasing your kingdom's Size by 1 (this affects all statistics determined by Size; see page 38).", failure: "You fail to claim the hex.", criticalFailure: "You fail to claim the hex, and a number of early settlers and explorers are lost, causing you to take a -1 circumstance penalty to Stability-based checks until the end of your next Kingdom turn." },
  },
  {
    id: "clandestine-business",
    name: "Clandestine Business",
    phase: "leadership",
    skills: [{ skill: "intrigue", minRank: 1 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You know there are criminals in your kingdom, and they know you know. You encourage them to send kickbacks in the form of resources and Commodities to the government, but the common citizens will be more than upset if they find out! This starts as a basic check against your Control DC, but every subsequent Kingdom turn you pursue Clandestine Business, the DC increases by 2. Every Kingdom turn that passes without Clandestine Business reduces the DC by 1 (until you reach your Control DC).",
    outcomes: { criticalSuccess: "Immediately roll 2 Resource Dice. Gain RP equal to the result. In addition, you gain 1d4 Luxury Commodities. The public is none the wiser.", success: "Either immediately roll 2 Resource Dice and gain RP equal to the result, or gain 1d4 Luxury Commodities. Regardless of your choice, rumors spread about where the government is getting these \"gifts.\" Increase Unrest by 1.", failure: "Immediately roll 1 Resource Die and gain RP equal to the result. Rumors are backed up with eyewitness accounts. Increase Unrest by 1 and Corruption by 1.", criticalFailure: "You gain nothing from the Clandestine Business but angry citizens. Increase Unrest by 1d6, Corruption by 2, and one other Ruin of your choice by 1." },
  },
  {
    id: "clear-hex",
    name: "Clear Hex",
    phase: "region",
    skills: [{ skill: "engineering", minRank: 0 }, { skill: "exploration", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: null,
    description: "Engineers and mercenaries attempt to prepare a hex to serve as the site for a settlement, or they work to remove an existing improvement, a dangerous hazard, or an encounter. If you're trying to prepare a hex for a settlement or demolish an improvement you previously built (or that was already present in the hex), spend RP as determined by the hex's most inhospitable terrain feature (see the Building on Rough Terrain sidebar nearby). Then attempt a basic Engineering check. If you're trying to remove a hazard or encounter, instead attempt an Exploration check. The DC of this check is set by the highest level creature or hazard in the hex (as set by Table 10-5: DCs by Level, on page 503 of the Pathfinder Core Rulebook). If the hex you're attempting to Clear has existing Ruins or an existing Structure, your action doesn't physically remove the buildings from the area and you can later incorporate these buildings (or repair ruined ones) into a Settlement you build here later. Regardless of the skill used, increase the basic DC by 2 if the hex to be cleared is not yet part of your kingdom.",
    outcomes: { criticalSuccess: "You successfully clear the hex. If you spent RP to attempt this activity, you're refunded half of the RP cost. If you were removing dangerous creatures (but not hazards) from the hex, your explorers and mercenaries recover 2 Luxury Commodities as treasure.", success: "You successfully clear the hex.", failure: "You fail to clear the hex.", criticalFailure: "You catastrophically fail to clear the hex and several workers lose their lives. Gain 1 Unrest." },
  },
  {
    id: "collect-taxes",
    name: "Collect Taxes",
    phase: "commerce",
    skills: [{ skill: "trade", minRank: 1 }],
    traits: ["COMMERCE", "DOWNTIME"],
    requirements: null,
    description: "Tax collectors travel through the lands to collect funds for the betterment of the kingdom. Attempt a basic check.",
    outcomes: { criticalSuccess: "Your tax collectors are wildly successful! For the remainder of the Kingdom turn, gain a +2 circumstance bonus to Economy-based checks.", success: "Your tax collectors gather enough to grant you a +1 circumstance bonus to Economy-based checks for the remainder of the Kingdom turn. If you attempted to Collect Taxes during the previous turn, increase Unrest by 1.", failure: "As success, but the people are unhappy about taxes—increase Unrest by 1 (or by 2 if you attempted to Collect Taxes the previous turn).", criticalFailure: "Your tax collectors encounter resistance from the citizens, and their attempts to gather taxes are rebuffed. While the tax collectors still manage to gather enough taxes to support essential government needs, they have angered the kingdom's citizens and encouraged rebellious acts. Increase Unrest by 2, and choose one Ruin to increase by 1." },
  },
  {
    id: "craft-luxuries",
    name: "Craft Luxuries",
    phase: "leadership",
    skills: [{ skill: "arts", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You encourage your artisans to craft luxury goods and may even aid them in this pursuit. Roll 1 Resource Die and spend RP equal to the result. Then attempt a basic check.",
    outcomes: { criticalSuccess: "Your artisans exceed expectations and craft extravagant goods. Gain 1d4 Luxury Commodities.", success: "Your artisans produce some delightful goods. Gain 1 Luxury Commodity.", failure: "Your artisans fail to produce anything noteworthy.", criticalFailure: "Your artisans not only fail to produce anything noteworthy, but some took advantage of the opportunity to push their own agendas or earn more for themselves by selling to underground markets. Increase one of your Ruins by 1." },
  },
  {
    id: "create-a-masterpiece",
    name: "Create a Masterpiece",
    phase: "leadership",
    skills: [{ skill: "arts", minRank: 1 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You encourage your kingdom's artists to create and display a masterful work of art to bolster your kingdom's reputation. Attempt a basic check; the result affects either Fame or Infamy (depending on the type of kingdom you're running). Create a Masterpiece may be attempted only once per Kingdom turn regardless of the number of leaders pursuing activities.",
    outcomes: { criticalSuccess: "Gain 1 Fame or Infamy point immediately, and at the start of your next Kingdom turn, gain 1 additional Fame or Infamy point. Immediately roll 2 Resource Dice. Gain RP equal to the result.", success: "Gain 1 Fame or Infamy point immediately.", failure: "Your attempt to create a masterpiece fails.", criticalFailure: "Not only does your attempt to create a masterpiece fail, it does so in a dramatic and humiliating way. Lose 1 Fame or Infamy point; if you have no Fame or Infamy points to lose, instead gain 1d4 Unrest." },
  },
  {
    id: "creative-solution",
    name: "Creative Solution",
    phase: "leadership",
    skills: [{ skill: "scholarship", minRank: 0 }],
    traits: ["DOWNTIME", "FORTUNE", "LEADERSHIP"],
    requirements: null,
    description: "You work with your kingdom's scholars, thinkers, and practitioners of magical and mundane experimentation to come up with new ways to resolve issues when business as usual is just not working. Attempt a basic check.",
    outcomes: { criticalSuccess: "You can call upon the solution to aid in resolving any Kingdom skill check made during the remainder of this Kingdom turn. Do so when a Kingdom skill check is rolled, but before you learn the result. Immediately reroll that check with a +2 circumstance bonus; you must take the new result. If you don't use your Creative Solution by the end of this turn, you lose this benefit and gain 10 kingdom XP instead.", success: "As critical success, but the Creative Solution costs the kingdom 1d4 RP to research. This cost is paid now, whether or not you use your Creative Solution.", failure: "Your attempt at researching a Creative Solution costs the kingdom 2d6 RP but is ultimately a failure. It provides no advantage.", criticalFailure: "As failure, but your scholars and thinkers are so frustrated that you take a -1 circumstance penalty to Culture-based checks until the end of the next Kingdom turn." },
  },
  {
    id: "demolish",
    name: "Demolish",
    phase: "civic",
    skills: [{ skill: "engineering", minRank: 0 }],
    traits: ["CIVIC", "DOWNTIME"],
    requirements: null,
    description: "Choose a single occupied lot in one of your settlements and attempt a basic check to reduce it to Rubble and then clear the Rubble away to make ready for a new structure. For multiple-lot structures, you'll need to perform multiple Demolish activities (or critically succeed at the activity) to fully clear all of the lots. As soon as you begin Demolishing a multiple-lot structure, all of the lots occupied by that structure no longer function.",
    outcomes: { criticalSuccess: "Choose one of the following effects: you demolish an entire multiple-lot structure all at once and clear all of the lots it occupied, or you recover 1d6 Commodities (chosen from lumber, stone, and ore) from the Rubble of a single-lot demolition.", success: "You demolish the lot successfully.", failure: "You fail to demolish the lot. It remains in Rubble and cannot be used for further construction until you successfully Demolish it.", criticalFailure: "As failure, but accidents during the demolition cost you the lives of some of your workers. Gain 1 Unrest." },
  },
  {
    id: "deploy-army",
    name: "Deploy Army",
    phase: "army",
    skills: [{ skill: "boating", minRank: 0 }, { skill: "exploration", minRank: 0 }, { skill: "magic", minRank: 0 }],
    traits: ["DOWNTIME", "ARMY"],
    requirements: null,
    description: "The army moves through your kingdom or beyond. Since this travel occurs over the course of the entire month that preceded the Kingdom turn, the ground an army covers when it deploys can be quite extensive. You can Deploy an Army with an Exploration, Boating, or Magic check. When you use an Exploration check, choose a location within 20 hexes of the army's current hex. If the army's starting point and ending point are connected by a road, increase the result one degree of success. Count roadless hexes that contain swamps or mountains, or each hex where you must cross a river or lake without the aid of a bridge, as two hexes.. You can issue orders to force march. Doing so grants a +4 circumstance bonus on the check, but causes the army to increase its weary condition by 1 (or by 2, if you fail the check). When you use a Boating check, the army's starting point and ending point must be connected by a body of water; choose any location within 20 hexes along this route. You must be at least master in Magic to attempt a Magic check. When you do so, choose any location within 30 hexes of the army's current hex, then roll your check. If the army's deployment causes it to cross your kingdom's border, the DC increases by 5. If the army's deployment causes it to cross an enemy kingdom's border, the DC instead increases by 10.",
    outcomes: { criticalSuccess: "The army arrives much more quickly than you anticipated; it arrives at its destination and then becomes efficient.", success: "The army arrives at its destination.", failure: "The army arrives at its destination, but ran into some sort of trouble along the way. Increase the army's weary condition by 1 and attempt a DC 6 flat check; on a failure, reduce the army's HP by 1.", criticalFailure: "Rather than arriving at its destination, the army becomes lost until it recovers from this condition. Increase Unrest by 1d4, and attempt a DC 11 flat check; on a failure, reduce the army's HP by 1." },
  },
  {
    id: "disband-army",
    name: "Disband Army",
    phase: "army",
    skills: [],
    traits: ["DOWNTIME", "ARMY"],
    requirements: null,
    description: "You can choose to disband an army with no check needed. If the army consisted of conscripts from your kingdom, the soldiers revert to being citizens. If the army was recruited from creatures encountered in the wilds, they return to their homes. A disbanded army no longer contributes to your kingdom's Consumption.",
    outcomes: {},
    skillChoice: "none",
  },
  {
    id: "establish-farmland",
    name: "Establish Farmland",
    phase: "region",
    skills: [{ skill: "agriculture", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "Plains or hills are the predominant terrain feature in the hex; the hex is in the influence of one of your settlements.",
    description: "You plant crops and establish livestock in permanent farms, ranches, and other growing operations to create Farmland (page 41). If you're attempting to Establish Farmland in a hex that is predominantly plains, you must spend 1 RP and the check is against your Control DC. If you're targeting a hex that is predominantly hills, you must spend 2 RP and the check is against your Control DC + 5.",
    outcomes: { criticalSuccess: "You establish two adjacent Farmland hexes instead of one. If your target hex was a hills hex, the additional hex may be a hills hex or a plains hex; otherwise, the additional hex must be a plains hex. If no appropriate hex is available, treat this result as a regular success instead.", success: "You establish one Farmland hex.", failure: "You fail to establish a Farmland hex.", criticalFailure: "You fail to establish a Farmland hex, and your attempt potentially causes the spread of a blight. At the start of each of the next two Event phases, attempt a DC 6 flat check; on a failure, your kingdom experiences a Crop Failure event in this and all adjacent hexes." },
  },
  {
    id: "establish-settlement",
    name: "Establish Settlement",
    phase: "region",
    skills: [{ skill: "engineering", minRank: 0 }, { skill: "industry", minRank: 0 }, { skill: "politics", minRank: 0 }, { skill: "scholarship", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "The hex in which you're establishing the settlement has been Cleared and doesn't currently have a settlement (including a Freehold) in it.",
    description: "You draw up plans, gather resources, entice citizens, and establish boundaries to found a brand new settlement in the hex. Attempt a basic Engineering, Industry, Politics, or Scholarship check. If you cannot pay the RP required by the result of this check, treat your result as a critical failure. A settlement always starts as a village. See page 46 for further details about building settlements.",
    outcomes: { criticalSuccess: "You establish the settlement largely with the aid of enthusiastic volunteers. Spend 1d6 RP.", success: "You establish the settlement. Spend 3d6 RP.", failure: "You establish the settlement, but inefficiently and at great expense. Spend 6d6 RP.", criticalFailure: "You fail to establish the settlement." },
  },
  {
    id: "establish-trade-agreement",
    name: "Establish Trade Agreement",
    phase: "leadership",
    skills: [{ skill: "boating", minRank: 0 }, { skill: "magic", minRank: 3 }, { skill: "trade", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: "You have diplomatic relations with the group you wish to establish an agreement with.",
    description: "You send a band of merchants out to establish a trade agreement between your kingdom and a group with whom you've established diplomatic relations. If a navigable river connects your kingdom with the other group's territory, you can attempt a Boating check to Establish the Trade Agreement. If your kingdom's proficiency rank in Magic is Master or higher, you can attempt a Magic check. Otherwise, attempt a Trade check. The check's DC is either the group's Negotiation DC (see sidebar) or your kingdom's Control DC, whichever is higher.",
    outcomes: { criticalSuccess: "You successfully establish a trade agreement with your target, and your merchants return with gifts! Immediately roll 2 Resource Dice, then gain RP equal to the result of roll.", success: "You successfully establish a trade agreement.", failure: "Your traders reach their destination but need to sweeten the deal to secure the trade agreement. Immediately roll 2 Resource Dice, and then spend RP equal to the result of this roll. If you do so, you successfully establish a trade agreement, otherwise the attempt fails.", criticalFailure: "Your trade agreement is a total loss and your traders do not return. Gain 1 Unrest, and until the end of the next Kingdom turn, take a -1 circumstance penalty to all Economy-related checks." },
  },
  {
    id: "establish-work-site",
    name: "Establish Work Site",
    phase: "region",
    skills: [{ skill: "engineering", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: null,
    description: "Your hire a crew of workers to travel to a hex that contains Lumber, Ore, or Stone to be harvested. Spend RP as determined by the hex's most inhospitable terrain (see the Building on Rough Terrain sidebar on page 23). Then attempt a basic check. Lumber camps can be established in any hex that contains a significant amount of forest terrain. Mines and quarries can be established in any hex that contains a significant amount of hill or mountain terrain.",
    outcomes: { criticalSuccess: "You establish a Work Site in the hex and proceed to discover an unexpectedly rich supply of high quality Commodities. All Commodity yields granted by this site are doubled until the end of the next Kingdom turn.", success: "You establish a Work Site in the hex.", failure: "You fail to establish a Work Site in the hex.", criticalFailure: "Not only do you fail to establish a Work Site, but you lose several workers to an accident, banditry, a vicious monster, or some other unforeseen occurrence. Gain 1 Unrest." },
  },
  {
    id: "focused-attention",
    name: "Focused Attention",
    phase: "leadership",
    skills: [],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You set aside time to focus attention on aiding another leader in an activity. Choose another leader and a Kingdom skill, then attempt a DC 20 check using the chosen skill. On a success, you grant that leader a +2 circumstance bonus to one kingdom check using that skill, provided that leader attempts the skill check during the same Kingdom turn. The Cooperative Leadership Kingdom feat (page 36) increases the efficiency of this activity.",
    outcomes: {},
    skillChoice: "any",
    anyMinRank: 0,
  },
  {
    id: "fortify-hex",
    name: "Fortify Hex",
    phase: "region",
    skills: [{ skill: "defense", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "The target hex must be claimed by your kingdom and must not have a settlement in it.",
    description: "Your command your engineers to construct a protected encampment, such as a fort or barbican, to serve as a defensive post in the hex. Spend RP as determined by the hex's most inhospitable terrain (see the Building on Rough Terrain sidebar on page 23). Then attempt a basic check. A fortified hex grants an additional bonus in warfare (see the appendix starting on page 71), but also gives traveling PCs a place to rest that prevents wandering monsters from interrupting their rest.",
    outcomes: { criticalSuccess: "You find a defensible position for your fortification and finish construction efficiently. Gain a refund of half the RP you spent to build in the hex, then reduce Unrest by 1.", success: "You establish your fortification in the hex. Reduce Unrest by 1.", failure: "You fail to fortify the hex.", criticalFailure: "Your attempt ends in disaster. Not only do you fail to build a structure, but you lose several workers to an accident, banditry, a vicious monster, or some other unforeseen occurrence. Gain 1 Unrest." },
  },
  {
    id: "garrison-army",
    name: "Garrison Army",
    phase: "army",
    skills: [{ skill: "defense", minRank: 0 }, { skill: "engineering", minRank: 0 }, { skill: "politics", minRank: 0 }],
    traits: ["DOWNTIME", "ARMY"],
    requirements: "The army is in the same hex as a Refuge, Settlement, or Work Site.",
    description: "You move an army into a fortification and assign them to guard it. In order to garrison, the army must be located in a hex that contains a Refuge, Settlement, or Work Site. If you're garrisoning the army in a Refuge hex, attempt a basic Defense check. If you're garrisoning the army in a settlement, attempt a basic Politics check. If you're garrisoning the army in a Work Site hex, attempt a basic Engineering check. This check's DC increases by 5 if the hex is not part of your kingdom, or by 10 if the location is part of an enemy kingdom.",
    outcomes: { criticalSuccess: "The army becomes fortified until it is deployed. Additionally, the efficiency of the garrisoning reduces this army's Consumption by 2 (to a minimum of 1) until it is deployed.", success: "The army becomes fortified until it is deployed.", failure: "The army becomes fortified until the next Kingdom turn begins, at which point you must use this activity again to maintain the fortified condition.", criticalFailure: "Your army clashes with local citizens, abuses their authority, lets their watchful readiness slack, and/or provokes confrontations where they are not needed. It does not become fortified, and you cannot attempt to garrison that army at this location again for 4 Kingdom turns. Increase Unrest by 1." },
  },
  {
    id: "gather-livestock",
    name: "Gather Livestock",
    phase: "region",
    skills: [{ skill: "wilderness", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: null,
    description: "Attempt a basic check to gather excess livestock from local wildlife, ranches, and farms. This generates a number of Food commodities.",
    outcomes: { criticalSuccess: "Gain 1d4 Food commodities.", success: "Gain 1 Food commodity.", failure: "Gain no Food commodities.", criticalFailure: "Lose 1d4 Food commodities to spoilage. If you have no Food to lose, you instead gain 1 Unrest. A kingdom gains feats as it increases in level. Some feats are general-purpose abilities that apply all the time. Others grant benefits to specific kingdom activities or events or allow kingdoms to perform special activities. Each time a kingdom gains a feat, players can select any feat whose level does not exceed their kingdom's level and whose prerequisites their kingdom satisfies." },
  },
  {
    id: "go-fishing",
    name: "Go Fishing",
    phase: "region",
    skills: [{ skill: "boating", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "Must have at least one claimed hex that includes river or lake terrain.",
    description: "Attempt a basic check to fish for food from the rivers and lakes in your kingdom.",
    outcomes: { criticalSuccess: "Gain 1d4 Food commodities.", success: "Gain 1 Food commodity.", failure: "Gain no Food commodities.", criticalFailure: "You lose some fishers to tragic accidents; gain 1 Unrest." },
  },
  {
    id: "harvest-crops",
    name: "Harvest Crops",
    phase: "region",
    skills: [{ skill: "agriculture", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: null,
    description: "Attempt a basic check to forage for wild edibles or gather excess crops from farms.",
    outcomes: { criticalSuccess: "Gain 1d4 Food commodities.", success: "Gain 1 Food commodity.", failure: "Gain no Food commodities.", criticalFailure: "Lose 1d4 Food commodities to spoilage; if you have no Food to lose, you instead gain 1 Unrest." },
  },
  {
    id: "hire-adventurers",
    name: "Hire Adventurers",
    phase: "leadership",
    skills: [{ skill: "exploration", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "While the PCs can strike out themselves to deal with ongoing events, it's often more efficient to Hire Adventurers. When you Hire Adventurers to help end an ongoing event, the DC is equal to your Control DC adjusted by the event's level modifier. Roll 1 Resource Die and spend RP equal to the result each time you attempt this activity.",
    outcomes: { criticalSuccess: "You end the continuous event.", success: "The continuous event doesn't end, but you gain a +2 circumstance bonus to resolve the event during the next Event phase.", failure: "You fail to end the continuous event. If you try to end the continuous event again, the cost in RP increases to 2 Resource Dice.", criticalFailure: "As failure, but word spreads quickly through the region—you can no longer attempt to end this continuous event by Hiring Adventurers." },
  },
  {
    id: "improve-lifestyle",
    name: "Improve Lifestyle",
    phase: "commerce",
    skills: [{ skill: "politics", minRank: 0 }],
    traits: ["COMMERCE", "DOWNTIME"],
    requirements: null,
    description: "Attempt a basic check to draw upon your kingdom's treasury to enhance the quality of life for your citizens. This activity can be taken only during the Commerce phase of a Kingdom turn (page 44).",
    outcomes: { criticalSuccess: "Your push to Improve Lifestyles affords your citizens significant free time to pursue recreational activities. For the remainder of the Kingdom turn, you gain a +2 circumstance bonus to Culture-based checks.", success: "Your push to Improve Lifestyles helps your citizens enjoy life. For the remainder of the Kingdom turn, you gain a +1 circumstance bonus to Culture‑based checks.", failure: "As success, but you've strained your treasury. Take a -1 circumstance penalty to Economy-based checks for the remainder of this Kingdom turn.", criticalFailure: "Your attempt to Improve Lifestyles backfires horribly as criminal elements in your kingdom abuse your generosity. You take a -1 circumstance penalty to Economy-based checks for the remainder of the Kingdom turn, gain 1 Unrest, and add 1 to a Ruin of your choice." },
  },
  {
    id: "infiltration",
    name: "Infiltration",
    phase: "leadership",
    skills: [{ skill: "intrigue", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You send spies out to gather intelligence on a neighboring nation, a cult or thieves' guild within your borders, an unclaimed Freehold, or even an unexplored adventure site. Alternately, you can simply send your spies out to investigate the current health of your kingdom. Attempt a basic check.",
    outcomes: { criticalSuccess: "You learn something valuable or helpful. If you were infiltrating a specific target, the GM decides what is learned, but the information is exact and precise. For example, if you were infiltrating an unexplored ruin, you might learn that the site is infested with web lurkers and spider swarms. If you were investigating your kingdom's health, your spies reveal easy methods to address citizen dissatisfaction, allowing you to choose one of the following: reduce Unrest by 1d4 or reduce a Ruin of your choice by 1.", success: "You learn something helpful about the target, but the information is vague and imprecise. For example, if you were infiltrating the same ruin mentioned in the critical success above, you might learn that some sort of aberration uses the ruins as its lair. If you were investigating your kingdom's health, your spies learn enough that you can take action. Reduce your kingdom's Unrest by 1.", failure: "Your spies fail to learn anything of import, but they are not themselves compromised.", criticalFailure: "You never hear from your spies again, but someone certainly does! You take a -2 circumstance penalty on all kingdom checks until the end of the next Kingdom turn as counter- infiltration from an unknown enemy tampers with your kingdom's inner workings." },
  },
  {
    id: "irrigation",
    name: "Irrigation",
    phase: "region",
    skills: [{ skill: "engineering", minRank: 1 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: "You control a hex adjacent to a river or lake that itself does not contain a river or lake.",
    description: "You send excavators to build waterways, canals, or drainage systems to convey water from areas that have natural access to a river or lake. Spend RP as determined by the hex's most inhospitable terrain feature (see the Building on Rough Terrain sidebar on page 23). Then attempt a basic check.",
    outcomes: { criticalSuccess: "The hex gains a river or lake terrain feature (or you change the effects of a previous critical failure at Irrigation in this hex into a failure); work with your GM to determine where these features appear in the hex. In addition, your workers were efficient and quick, and you regain half the RP you spent building the waterways.", success: "As success, but without regaining any RP.", failure: "You fail to build workable systems or to restore a previous critical failure, and the hex does not gain the river or lake terrain feature.", criticalFailure: "As failure, but your attempts at Irrigation are so completely useless that they become breeding grounds for disease. Gain 1 Unrest. From this point onward, at the start of your Kingdom turn's Event phase, attempt a DC 4 flat check. This flat check's DC increases by 1 for each hex in your kingdom that contains a critically failed attempt at Irrigation. If you fail this flat check, your kingdom suffers a Plague event in addition to any other event it might have. You can attempt this activity again in a later Kingdom turn to undo a critically failed Irrigation attempt." },
  },
  {
    id: "manage-trade-agreements",
    name: "Manage Trade Agreements",
    phase: "commerce",
    skills: [{ skill: "trade", minRank: 0 }],
    traits: ["COMMERCE", "DOWNTIME"],
    requirements: null,
    description: "You send agents out to attend to established trade agreements. Spend 2 RP per Trade Agreement you wish to manage. Then attempt a basic check. If you Managed Trade Agreements on the previous turn, increase this DC by 5.",
    outcomes: { criticalSuccess: "At the start of your next Kingdom turn, you gain 1 bonus Resource Die per trade agreement, and 1 Commodity of your choice per trade agreement (no more than half of these Commodities may be Luxuries).", success: "As critical success, but you must choose between gaining Resource Dice or Commodities.", failure: "You gain 1 RP per trade agreement at the start of your next turn.", criticalFailure: "You gain no benefit, as your traders and merchants met with bad luck on the road. You can't Manage Trade Agreements for 1 Kingdom turn." },
  },
  {
    id: "new-leadership",
    name: "New Leadership",
    phase: "leadership",
    skills: [{ skill: "intrigue", minRank: 0 }, { skill: "politics", minRank: 0 }, { skill: "statecraft", minRank: 0 }, { skill: "warfare", minRank: 0 }],
    traits: ["DOWNTIME"],
    requirements: null,
    description: "You announce the promotion of a character into a leadership role, whether they're a newly appointed leader or just shifting from one leadership role to another. You normally perform this activity at the start of a Kingdom turn, but if unexpected events (such as the death of the character) remove a leader from a leadership role, you may immediately use the New Leadership activity to attempt to assign a new leader to that role, even outside of a Kingdom turn (applying the vacancy penalty for that role as appropriate). Attempt a basic Intrigue, Politics, Statecraft, or Warfare skill check—while any of these skills can be used, each skill is particularly suited to assigning two specific leadership roles. • Intrigue: Grants a +2 circumstance bonus to checks to assign Emissaries and Treasurers. • Politics: Grants a +2 circumstance bonus to checks to assign Counselors and Rulers. • Statecraft: Grants a +2 circumstance bonus to checks to assign Magisters and Viceroys. • Warfare: Grants a +2 circumstance bonus to checks to assign Generals and Wardens. Rulers are particularly difficult to assign; when you take this activity to assign a new Ruler, you take a -4 circumstance penalty to the skill check, and unless you achieve a critical success, you gain 1 additional Unrest. Whether or not you are simultaneously assigning a leader, you may also use this activity to attempt to reselect the four leadership roles that you have invested. Any result other than a critical failure allows this.",
    outcomes: { criticalSuccess: "The people love the new leader. The leader immediately provides the benefits tied to occupying the new role and gains a +1 circumstance bonus to all Kingdom skill checks they attempt before the end of the next Kingdom turn.", success: "The people accept the new leader. The leader immediately provides the benefits tied to occupying the new role.", failure: "The people are unsure about the new leader. The leader takes a -1 circumstance penalty to all checks they attempt as part of their activities during the Activity phase of each Kingdom turn. At the end of the next Kingdom turn, the leader can attempt any Loyalty‑based basic skill check to ingratiate themselves with the populace. The leader may attempt this check at the end of each Kingdom turn until they succeed. Success removes this penalty, but a critical failure results in the development detailed in Critical Failure below.", criticalFailure: "The people reject the new leader. The leadership role is treated as vacant and you must attempt to reassign it using the New Leadership activity at the start of the next Kingdom turn. Unrest increases by 1." },
  },
  {
    id: "offensive-gambit",
    name: "Offensive Gambit",
    phase: "army",
    skills: [{ skill: "intrigue", minRank: 0 }, { skill: "warfare", minRank: 0 }],
    traits: ["DOWNTIME", "ARMY"],
    requirements: "You have at least one army in the same hex as an enemy army.",
    description: "You order an attack against an enemy army, causing a war encounter to begin after this Kingdom turn ends. No check is necessary if you wish to engage the enemy without attempting to gain an advantage in initiative. If you want to gain an advantage by surprising the enemy, attempt an Intrigue check. If you want to gain an advantage by intimidating the enemy, attempt a Warfare check. In either case, the DC is equal to the enemy army's Scouting DC.",
    outcomes: { criticalSuccess: "Your approach surprises or intimidates the enemy. Your armies in this hex gain a +2 circumstance bonus on their initiative checks, and one enemy army of the party's choice in this hex becomes shaken 1.", success: "Your approach gives you an advantage. Your armies in this hex gain a +2 circumstance bonus on their initiative checks.", failure: "You gain no advantage in the battle.", criticalFailure: "Not only do you fail to gain advantage, but the enemy forces have anticipated the attack. Enemy armies in this hex at the time of the Offensive Gambit gain a +4 circumstance bonus on their initiative checks in any resulting war encounters." },
  },
  {
    id: "outfit-army",
    name: "Outfit Army",
    phase: "army",
    skills: [],
    traits: ["DOWNTIME", "ARMY"],
    requirements: null,
    description: "You provide your army with better gear. Choose what sort of gear you wish to provide your army with from the list beginning on page 67. The level of the gear chosen must be equal to or less than the army's level. If you're crafting or purchasing gear, the level of the gear chosen must be equal to or less than your kingdom level. If you're distributing resources gained from battle, the level of the gear chosen must be equal to or less than the highest level of an enemy army defeated in that battle. If you're purchasing the gear, this activity requires a basic Trade check and costs the standard amount of RP for the gear; you cannot purchase magic gear unless your kingdom is at least expert rank in Magic. If you're distributing gear gained from battle, this activity requires a basic Warfare check and does not cost RP.",
    outcomes: { criticalSuccess: "The gear proved particularly easy to outfit, and the army becomes efficient.", success: "The gear is sufficient, and your army becomes outfitted with it immediately.", failure: "The gear proves to be unusable and the attempt to outfit the army fails. If you spent RP on the check, it is refunded. Trained Activities — Recover Weary Army (expert) — — — — — — — — Recover Damaged Army (expert) — Deploy Army (master) Recover Mired or Pinned Army (expert) Recover Defeated Army (master) — — — Recover Defeated Army (expert) Recover Shaken Army (expert) — — Recover Lost Army (expert)", criticalFailure: "As failure, but spent RP is not refunded." },
    skillChoice: "none",
  },
  {
    id: "pledge-of-fealty",
    name: "Pledge of Fealty",
    phase: "leadership",
    skills: [{ skill: "intrigue", minRank: 1 }, { skill: "statecraft", minRank: 1 }, { skill: "warfare", minRank: 1 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "When your representatives encounter freeholders, refugees, independent groups, or other bands of individuals gathered in the wilderness who aren't already part of a nation, you can offer them a place in your kingdom, granting them the benefits of protection, security, and prosperity in exchange for their fealty. The benefits granted to your kingdom can vary wildly, but often manifest as one-time boons to your commodities or unique bonuses against certain types of events. The adventure text in this campaign offers numerous examples of groups who could accept a Pledge of Fealty. You can attempt this skill check with Intrigue, Statecraft, or Warfare; however, certain groups will respond better (or worse) to specific skills. The DC is the group's Negotiation DC (see the sidebar on page 23).",
    outcomes: { criticalSuccess: "The group becomes part of your kingdom, granting the specific boon or advantage listed in that group's entry. If you haven't already claimed the hex in which the group dwells, you immediately do so, gaining 10 kingdom XP and increasing your kingdom's Size by 1 (this affects all statistics determined by Size; see page 38). If the hex doesn't share a border with your kingdom, it becomes a secondary territory and checks involving this location take a Control penalty.", success: "As success, but you don't claim the hex the group is in. Immediately roll 1 Resource Die. You must spend RP equal to the result to integrate the group into your kingdom.", failure: "The group refuses to pledge to you at this time. You can attempt to get them to Pledge Fealty next turn. Increase Unrest by 1.", criticalFailure: "The group refuses to pledge to you— furthermore, it will never Pledge Fealty to your kingdom, barring significant in-play changes or actions by the PCs (subject to the GM's approval). The group's potentially violent rebuff of your offer increases Unrest by 2 and increases a Ruin of your choice by 1." },
  },
  {
    id: "prognostication",
    name: "Prognostication",
    phase: "leadership",
    skills: [{ skill: "magic", minRank: 1 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "Your kingdom's spellcasters read the omens and provide advice on how best to prepare for near-future events. Attempt a basic check.",
    outcomes: { criticalSuccess: "If you have a random kingdom event this turn, roll twice to determine the event that takes place. The players choose which of the two results occurs, and the kingdom gains a +2 circumstance bonus to the check to resolve the event.", success: "Gain a +1 circumstance bonus to checks made to resolve random kingdom events this turn.", failure: "Your spellcasters divine no aid.", criticalFailure: "Your spellcasters provide inaccurate readings of the future. You automatically have a random kingdom event this turn. Roll twice to determine the event that takes place; the GM decides which of the two results occurs." },
  },
  {
    id: "provide-care",
    name: "Provide Care",
    phase: "leadership",
    skills: [{ skill: "defense", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "Attempt a basic check to organize and encourage your settlements' healers, apothecaries, medics, and other caregivers to provide care and support for citizens in need.",
    outcomes: { criticalSuccess: "You provide unexpectedly compassionate support for the people. Reduce Unrest by 1 and reduce one Ruin of your choice by 1.", success: "Your care soothes the worries and fears of the populace; reduce Unrest by 1.", failure: "You don't provide any notable care for the citizens, but at least you don't make things worse.", criticalFailure: "Your attempt to provide care backfires. Increase your Unrest or a Ruin of your choice by 1." },
  },
  {
    id: "purchase-commodities",
    name: "Purchase Commodities",
    phase: "leadership",
    skills: [{ skill: "trade", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You can spend RP to Purchase Commodities, but doing so is more expensive than gathering them or relying upon trade agreements. When you Purchase Commodities, select the Commodity you wish to purchase (Food, Lumber, Luxuries, Ore, or Stone). Expend 8 RP if you're purchasing Luxuries or 4 RP if you're purchasing any other Commodity. Then attempt a basic check.",
    outcomes: { criticalSuccess: "You immediately gain 4 Commodities of the chosen type and 2 Commodities of any other type (except Luxuries).", success: "You gain 2 Commodities of the chosen type.", failure: "You gain 1 Commodity of the chosen type.", criticalFailure: "You gain no Commodities." },
  },
  {
    id: "quell-unrest",
    name: "Quell Unrest",
    phase: "leadership",
    skills: [{ skill: "arts", minRank: 0 }, { skill: "folklore", minRank: 0 }, { skill: "intrigue", minRank: 0 }, { skill: "magic", minRank: 0 }, { skill: "politics", minRank: 0 }, { skill: "warfare", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You send your agents among the citizenry with the charge of suppressing dissent and calming unrest. You can attempt a basic Arts, Folklore, Intrigue, Magic, Politics, or Warfare check to Quell Unrest, but you can never use the same skill for this activity in consecutive Kingdom turns. This activity cannot be attempted more than once per Kingdom turn.",
    outcomes: { criticalSuccess: "Reduce Unrest by 1d6.", success: "Reduce Unrest by 1.", failure: "You fail to reduce Unrest.", criticalFailure: "You not only fail to reduce Unrest, but actually incite further anger among the citizenry. Choose one of the following: increase Unrest by 1d4 or increase two Ruins of your choice by 1." },
  },
  {
    id: "reconnoiter-hex",
    name: "Reconnoiter Hex",
    phase: "region",
    skills: [{ skill: "exploration", minRank: 0 }, { skill: "wilderness", minRank: 0 }],
    traits: ["DOWNTIME", "REGION"],
    requirements: null,
    description: "You send a team to spend time surveying and exploring a specific hex, getting the lay of the land and looking for unusual features and specific sites. Spend 1 RP and then attempt a basic check.",
    outcomes: { criticalSuccess: "The hex is now Reconnoitered for the purpose of Claim Hex. Your team automatically finds one Special or Hidden feature if the hex contains one, and avoids any Encounter or Hazard while reporting detailed information on it. You may immediately attempt an additional Reconnoiter Hex activity on an adjacent hex; treat a critical success on that check as a success instead.", success: "The hex is now Reconnoitered for the purpose of Claim Hex. If the hex contains a Special feature your team may find it if your GM wishes. The team avoids any Encounter or Hazard and reports basic information.", failure: "Your team fails to explore the hex sufficiently. The team escapes any Encounter or Hazard and reports basic information on it.", criticalFailure: "Your team fails to explore the hex sufficiently and a number of the team are lost, causing you to take a -1 circumstance penalty to Loyalty-based checks until the end of your next Kingdom turn." },
    source: "VK",
  },
  {
    id: "recover-army",
    name: "Recover Army",
    phase: "army",
    skills: [],
    traits: ["DOWNTIME", "ARMY"],
    requirements: null,
    description: "When an army endures ill fortune, it can become afflicted by negative conditions. You can use the Recover Army activity to work at removing an affliction with a basic skill check (this DC increases by 5 if you are attempting to Recover from the defeated condition); the skill required for the check depends on the affliction (see the table on page 64).",
    outcomes: { criticalSuccess: "You reduce the affliction's value by 2 (or in the case of a damaged army, increase its HP by 2 up to its maximum). If the affliction does not have a value, it is removed.", success: "As critical success but you reduce the affliction's value by 1 (or in the case of a damaged army, increase its HP by 1 up to its maximum).", failure: "You fail to remove the affliction.", criticalFailure: "You fail to remove the affliction and your soldier's lowered morale spreads discontent; increase Unrest by 1. If you were attempting to recover a defeated army, the army is destroyed." },
    skillChoice: "varies",
  },
  {
    id: "recruit-army",
    name: "Recruit Army",
    phase: "leadership",
    skills: [{ skill: "statecraft", minRank: 0 }, { skill: "warfare", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "Note that you pursue this activity during the Leadership step of the Activity phase. Either you recruit an army from your kingdom's citizens, or you secure the allegiance of a specialized army you encountered in the Stolen Lands. If you're recruiting an army from your kingdom's citizens, choose one of the basic armies listed at the start of page 66 and attempt a Warfare check against the army's Recruitment DC. If you're securing a specialized army, you must attempt a Statecraft check against the Recruitment DC; statistics for these armies are available to your GM and will be revealed during play.",
    outcomes: { criticalSuccess: "You recruit the army; it becomes efficient.", success: "You recruit the army.", failure: "You fail to recruit the army.", criticalFailure: "Many of the individuals in the army you attempted to recruit took offense at the attempt. Gain 1 Unrest, and you cannot attempt to recruit an army again until the next Kingdom turn." },
  },
  {
    id: "relocate-capital",
    name: "Relocate Capital",
    phase: "leadership",
    skills: [{ skill: "industry", minRank: 1 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: "One of your settlements that is not your current capital must contain a Castle, Palace, or Town Hall. All leaders must spend all of their leadership activities during the Activity phase of a Kingdom turn on this activity.",
    description: "The kingdom leaders announce that they are uprooting the seat of government from its current home and reestablishing it in another settlement. Attempt a check with a DC equal to the kingdom's Control DC + 5. You cannot Relocate your Capital again for at least 3 Kingdom turns.",
    outcomes: { criticalSuccess: "The move goes off splendidly, with people excited about the new capital and celebrating the leadership's wisdom.", success: "The move goes smoothly and with minimal disruption, but some folks are upset or homesick. Increase Unrest by 1.", failure: "The move causes unhappiness. Gain 1 Unrest and increase two Ruins of your choice by 1.", criticalFailure: "The people reject the idea of the new capital and demand you move it back. The move is unsuccessful, and your capital remains unchanged. Gain 1d4 Unrest. Increase three Ruins of your choice by 1 and the fourth Ruin by 3." },
  },
  {
    id: "repair-reputation",
    name: "Repair Reputation",
    phase: "leadership",
    skills: [{ skill: "arts", minRank: 0 }, { skill: "engineering", minRank: 0 }, { skill: "intrigue", minRank: 0 }, { skill: "trade", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "When things have gotten out of hand in the kingdom and the nation's reputation has become damaged, you can focus efforts on a campaign to reassure the citizens and bring them closer together, stamp down crime, organize repairs and maintenance of public structures, or strive to adjust poor public opinions. The skill used to Repair Reputation depends on which Ruin total you wish to reduce. If you wish to reduce your Corruption, you attempt an Arts check. If you wish to reduce your Crime, you attempt a Trade check. If you wish to reduce your Decay, you attempt an Engineering check. If you wish to reduce your Strife, you attempt an Intrigue check. In all cases, the DC is your Control DC + 2.",
    outcomes: { criticalSuccess: "You reduce the targeted Ruin by 2 and reduce its current ruin penalty by 1 to a minimum of 0.", success: "You reduce the targeted Ruin by 1.", failure: "You fail to reduce the targeted Ruin. You cannot attempt to Repair Reputation on this Ruin for 1 Kingdom turn.", criticalFailure: "You fail to reduce the targeted Ruin in a particularly public and embarrassing way. Increase Unrest by 1d4, and you cannot attempt to Repair Reputation for 3 Kingdom turns." },
  },
  {
    id: "request-foreign-aid",
    name: "Request Foreign Aid",
    phase: "leadership",
    skills: [{ skill: "statecraft", minRank: 1 }],
    traits: ["DOWNTIME", "LEADERSHIP", "QUEST"],
    requirements: "You have diplomatic relations with the group you are requesting aid from. Traveling scholar Tamerak Elenark has long been intrigued by the fact that once, eons ago, an entire civilization of cyclopes ruled a vast empire in northwestern Iobaria. The stories he's read in countless tomes have only fueled his curiosity, and he dreams of making a new discovery about these ancient people. Unfortunately, the lands where these cyclopes once ruled are now remote and dangerous—particularly to a mild-mannered scholar like Tamerak. Still, he pushes himself as much as he can and is eager to travel to the Stolen Lands and hire help for his complex research. Trigger: Once you build your first Academy or Museum in a settlement, Tamerak soon arrives in the kingdom to make his request, promising a magic pendant in return for assistance in his research.",
    description: "When disaster strikes, you send out a call for help to another nation with whom you have diplomatic relations. The DC of this check is equal to the other group's Negotiation DC +2 (see the sidebar on page 23).",
    outcomes: { criticalSuccess: "Your ally's aid grants a +4 circumstance bonus to any one Kingdom skill check attempted during the remainder of this Kingdom turn. You can choose to apply this bonus to any Kingdom skill check after the die is rolled, but must do so before the result is known. In addition, immediately roll 2 Resource Dice and gain RP equal to the result; this RP does not accrue into XP at the end of the turn if you don't spend it.", success: "As success, but choose the benefit given by the aid: either roll 1 Resource Die and gain RP equal to the result or gain a +2 circumstance bonus to a check.", failure: "Your ally marshals its resources but cannot get aid to you in time to deal with your current situation. At the start of your next Kingdom turn, gain 1d4 RP.", criticalFailure: "Your ally is tangled up in its own problems and is unable to assist you, is insulted by your request for aid, or might even have an interest in seeing your kingdom struggle against one of your ongoing events. Whatever the case, your pleas for aid make your kingdom look desperate. You gain no aid, but you do increase Unrest by 1d4." },
    vkNote: "The DC starts at the other group's Negotiation DC +2 and rises by 2 each consecutive turn you Request Foreign Aid from the same group, falling by 1 for each turn you do not (never below Negotiation DC +2). You may only request aid from a given group once per Kingdom turn.",
  },
  {
    id: "rest-and-relax",
    name: "Rest and Relax",
    phase: "leadership",
    skills: [{ skill: "arts", minRank: 0 }, { skill: "boating", minRank: 0 }, { skill: "scholarship", minRank: 0 }, { skill: "trade", minRank: 0 }, { skill: "wilderness", minRank: 0 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "Working non-stop can burn out even the most devoted and dedicated individual. As such, it's important to take time for yourself, and thus set a good example for the nation. You take time to relax, and you extend the chance to unwind to your citizens as well. The Kingdom skill you use to determine the effectiveness of your time off depends on how you want to spend it: Use a basic Arts check to spend the time engaged in entertainment or the pursuit of a hobby. Use a basic Boating check to enjoy trips on the lakes and rivers of your kingdom. Use a basic Scholarship check to spend the time reading or studying a topic of personal interest beyond your daily duties. Use a basic Trade check to spend your time shopping or feasting. Use a basic Wilderness check to get away from the bustle and relax in the countryside. If your kingdom Rested and Relaxed the previous Kingdom turn, the DC increases by 4, as your kingdom's production and output hasn't had a chance to catch up to all those vacation days.",
    outcomes: { criticalSuccess: "The citizens enjoy the time off and are ready to get back to work. Reduce Unrest by 1, and the next Leadership activity you take gains a +2 circumstance bonus.", success: "The time spent relaxing has calmed nerves; reduce Unrest by 1.", failure: "The rest is welcome, but not particularly beneficial in the long term.", criticalFailure: "The time is wasted, and when you get back to work, you have to spend extra time catching up. Take a -2 circumstance penalty to your next skill check made as a Leadership activity." },
  },
  {
    id: "send-diplomatic-envoy",
    name: "Send Diplomatic Envoy",
    phase: "leadership",
    skills: [{ skill: "statecraft", minRank: 1 }],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: null,
    description: "You send emissaries to another group to foster positive relations and communication. The DC of this check is the group's Negotiation DC (see the sidebar on page 23). Attempts to Send a Diplomatic Envoy to a nation with which your kingdom is at war take a -4 circumstance penalty to the check and have the result worsened one degree. At the GM's option, some wars might be so heated that this activity has no chance of success.",
    outcomes: { criticalSuccess: "Your envoys are received quite warmly and make a good first impression. You establish diplomatic relations with the group and gain a +2 circumstance bonus to all checks made with that group until the next Kingdom turn.", success: "You establish diplomatic relations.", failure: "Your envoys are received, but the target organization isn't ready to engage in diplomatic relations. If you attempt to Send a Diplomatic Envoy to the group next Kingdom turn, you gain a +2 circumstance bonus to that check.", criticalFailure: "Disaster! Your envoy fails to reach their destination, is turned back at the border, or is taken prisoner or executed, at the GM's discretion. The repercussions on your kingdom's morale and reputation are significant. Choose one of the following results: gain 1d4 Unrest, add 1 to a Ruin of your choice, or immediately roll 2 Resource Dice and spend RP equal to the result. In any event, you cannot attempt to Send a Diplomatic Envoy to this same target for the next 3 Kingdom turns. The first time your kingdom succeeds at establishing diplomatic relations in the campaign, gain 60 kingdom XP as a milestone award." },
  },
  {
    id: "supernatural-solution",
    name: "Supernatural Solution",
    phase: "leadership",
    skills: [{ skill: "magic", minRank: 0 }],
    traits: ["DOWNTIME", "FORTUNE", "LEADERSHIP"],
    requirements: null,
    description: "Your spellcasters try to resolve issues when mundane solutions just aren't enough. Attempt a basic check.",
    outcomes: { criticalSuccess: "You can call upon your spellcasters' supernatural solution to aid in resolving any Kingdom skill check made during the remainder of this Kingdom turn. Do so just before a Kingdom skill check is rolled (by yourself or any other PC). Attempt a Magic check against the same DC in addition to the Kingdom skill check, and take whichever of the two results you prefer. If you don't use your Supernatural Solution by the end of this Kingdom turn, this benefit ends and you gain 10 kingdom XP instead.", success: "As critical success, but the solution costs the kingdom 1d4 RP to research. This cost is paid now, whether or not you use your supernatural solution.", failure: "Your attempt at researching a supernatural solution costs the kingdom 2d6 RP, but is ultimately a failure, providing no advantage.", criticalFailure: "As failure, but your spellcasters' resources and morale are impacted such that you cannot attempt a Supernatural Solution again for 2 Kingdom turns." },
  },
  {
    id: "take-charge",
    name: "Take Charge",
    phase: "leadership",
    skills: [],
    traits: ["DOWNTIME", "LEADERSHIP"],
    requirements: "Your kingdom must be at least Trained in the chosen skill.",
    description: "You spend some time getting directly involved in helping your kingdom. Choose a skill that your kingdom is at least Trained in, then attempt a basic check. You can never use the same skill for this activity twice in the same Kingdom turn.",
    outcomes: { criticalSuccess: "Gain 1 RP. In addition you get a +1 circumstance bonus to the next check you make this turn with the chosen skill.", success: "Gain 1 RP.", failure: "You fail to generate RP.", criticalFailure: "You take a -1 circumstance penalty to the next check you make this turn with the chosen skill." },
    skillChoice: "any",
    anyMinRank: 1,
    source: "VK",
  },
  {
    id: "tap-treasury",
    name: "Tap Treasury",
    phase: "commerce",
    skills: [{ skill: "statecraft", minRank: 0 }],
    traits: ["COMMERCE", "DOWNTIME"],
    requirements: null,
    description: "You tap into the cash reserves of your kingdom for the PCs' personal use or to provide emergency funding for an event. This is a basic check, but after you succeed or critically succeed at this activity, all future attempts to Tap Treasury have their results worsened two degrees. This penalty persists until funds equal to those taken from the treasury are repaid via Capital Investment (page 34).",
    outcomes: { criticalSuccess: "You withdraw funds equal to the Currency per Additional PC column on Table 10-9: Party Treasure By Level on page 509 of the Pathfinder Core Rulebook (using your kingdom's level to set the amount), or you successfully fund the unexpected event that required you to Tap your Treasury.", success: "As critical success, but you overdraw your treasury in the attempt. You take a -1 circumstance penalty to all Economy-based checks until the end of your next Kingdom turn.", failure: "You fail to secure the funds you need, and rumors about the kingdom's potential shortfall of cash cause you to take a -1 circumstance penalty to all Loyalty- and Economy-based checks until the end of your next Kingdom turn.", criticalFailure: "As failure, but the rumors spiral out of control. Increase Unrest by 1 and add 1 to a Ruin of your choice." },
  },
  {
    id: "trade-commodities",
    name: "Trade Commodities",
    phase: "commerce",
    skills: [{ skill: "industry", minRank: 0 }],
    traits: ["COMMERCE", "DOWNTIME"],
    requirements: null,
    description: "There are five different categories of Commodities: Food, Lumber, Luxuries, Ore, and Stone. When you Trade Commodities, select one Commodity that your kingdom currently stockpiles and reduce that Commodity's stockpile by up to 4. Then attempt a basic check. If you trade with a group that you've established diplomatic relations with, you gain a +1 circumstance bonus to the check.",
    outcomes: { criticalSuccess: "At the beginning of the next Kingdom turn, you gain 2 bonus Resource Dice per point of stockpile expended from your Commodity now.", success: "At the beginning of your next Kingdom turn, you gain 1 bonus Resource Die per point of stockpile expended from your Commodity now.", failure: "You gain 1 bonus Resource Die at the beginning of your next Kingdom turn.", criticalFailure: "You gain no bonus Resource Dice (though the Commodity remains depleted). If you Traded Commodities the previous turn, gain 1 Unrest." },
  },
  {
    id: "train-army",
    name: "Train Army",
    phase: "army",
    skills: [{ skill: "scholarship", minRank: 0 }, { skill: "warfare", minRank: 0 }],
    traits: ["DOWNTIME", "ARMY"],
    requirements: null,
    description: "You train an army in the use of a tactic. Choose one of the tactics from those listed starting on page 68, then attempt a Scholarship or Warfare check against the tactic's Training DC. If your army has already learned its maximum number of tactics, the newly learned tactic replaces a previously learned tactic of your choice.",
    outcomes: { criticalSuccess: "The army learns the tactic and then becomes efficient.", success: "The army learns the tactic.", failure: "The army fails to learn the tactic.", criticalFailure: "The army not only fails to learn the tactic but becomes frustrated and exhausted from the training; increase the army's weary condition by 1." },
  },
];

export function getKingdomActivity(id: string): KingdomActivityDef | undefined {
  return KINGDOM_ACTIVITIES.find((a) => a.id === id);
}

/** Activities available during a given step of the Kingdom turn. */
export function activitiesForPhase(phase: ActivityPhase): KingdomActivityDef[] {
  return KINGDOM_ACTIVITIES.filter((a) => a.phase === phase);
}

/**
 * Activities a kingdom can attempt with `skill` at `rank`, including the
 * any-skill activities whose rank requirement it meets. Build Structure is
 * excluded: its skill comes from the structure, not from this list.
 */
export function activitiesForSkill(
  skill: string,
  rank: ProficiencyRank,
): KingdomActivityDef[] {
  return KINGDOM_ACTIVITIES.filter(
    (a) =>
      (a.skillChoice === "any" && rank >= (a.anyMinRank ?? 0)) ||
      a.skills.some((s) => s.skill === skill && rank >= s.minRank),
  );
}
