/**
 * PF2e Item Seed Data
 *
 * A curated catalog of common adventuring gear, weapons, armor,
 * containers, and consumables relevant to a Kingmaker campaign.
 *
 * Price is stored in copper pieces (cp). 1 gp = 100 cp, 1 sp = 10 cp.
 * Bulk: bulkValue=1 means 1 Bulk, isBulkLight=true means "L".
 * For negligible items: bulkValue=0, isBulkLight=false.
 */

import type { Rarity, ItemCategory } from "@/generated/prisma/client";

export interface SeedItem {
  name: string;
  bulkValue: number;
  isBulkLight: boolean;
  level: number;
  rarity: Rarity;
  traits: string[];
  category: ItemCategory;
  valueCp: number;
  isInvestable: boolean;
  containerCapacity: number | null;
  containerBulkReduction: number | null;
  description: string | null;
}

export const SEED_ITEMS: SeedItem[] = [
  // ── Containers ──────────────────────────────────────────
  {
    name: "Backpack",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "CONTAINER",
    valueCp: 10,
    isInvestable: false,
    containerCapacity: 4,
    containerBulkReduction: 2,
    description: "A worn backpack reduces the bulk of items inside by 2 (minimum 0). It can hold up to 4 Bulk.",
  },
  {
    name: "Belt Pouch",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "CONTAINER",
    valueCp: 10,
    isInvestable: false,
    containerCapacity: 0.4,
    containerBulkReduction: 0,
    description: "A small pouch that can hold up to 4 light items.",
  },
  {
    name: "Sack",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "CONTAINER",
    valueCp: 1,
    isInvestable: false,
    containerCapacity: 8,
    containerBulkReduction: 0,
    description: "A carried sack that can hold up to 8 Bulk.",
  },
  {
    name: "Saddlebags",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "CONTAINER",
    valueCp: 20,
    isInvestable: false,
    containerCapacity: 4,
    containerBulkReduction: 2,
    description: "Saddlebags for a mount. Reduces bulk of contents by 2 (up to 4 Bulk).",
  },
  {
    name: "Bag of Holding (Type I)",
    bulkValue: 1,
    isBulkLight: false,
    level: 4,
    rarity: "UNCOMMON",
    traits: ["Conjuration", "Extradimensional", "Magical"],
    category: "CONTAINER",
    valueCp: 7500,
    isInvestable: false,
    containerCapacity: 25,
    containerBulkReduction: 25,
    description: "Extradimensional container. Holds 25 Bulk, always weighs 1 Bulk. Items inside weigh nothing.",
  },

  // ── Weapons ─────────────────────────────────────────────
  {
    name: "Longsword",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: ["Versatile P"],
    category: "WEAPON",
    valueCp: 100,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Martial weapon. 1d8 S damage.",
  },
  {
    name: "Dagger",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: ["Agile", "Finesse", "Thrown 10 ft", "Versatile S"],
    category: "WEAPON",
    valueCp: 20,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Simple weapon. 1d4 P damage.",
  },
  {
    name: "Shortbow",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: ["Deadly d10"],
    category: "WEAPON",
    valueCp: 300,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Martial weapon. 1d6 P damage. Range 60 ft.",
  },
  {
    name: "Longbow",
    bulkValue: 2,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: ["Deadly d10", "Volley 30 ft"],
    category: "WEAPON",
    valueCp: 600,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Martial weapon. 1d8 P damage. Range 100 ft.",
  },
  {
    name: "Staff",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: ["Two-Hand d8"],
    category: "WEAPON",
    valueCp: 0,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Simple weapon. 1d4 B damage.",
  },
  {
    name: "Greatsword",
    bulkValue: 2,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: ["Versatile P"],
    category: "WEAPON",
    valueCp: 200,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Martial weapon. 1d12 S damage.",
  },
  {
    name: "Rapier",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: ["Deadly d8", "Disarm", "Finesse"],
    category: "WEAPON",
    valueCp: 200,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Martial weapon. 1d6 P damage.",
  },

  // ── Armor ───────────────────────────────────────────────
  {
    name: "Leather Armor",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "ARMOR",
    valueCp: 200,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Light armor. +1 AC, Dex cap +4.",
  },
  {
    name: "Chain Mail",
    bulkValue: 2,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: ["Flexible", "Noisy"],
    category: "ARMOR",
    valueCp: 600,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Medium armor. +4 AC, Dex cap +1.",
  },
  {
    name: "Full Plate",
    bulkValue: 4,
    isBulkLight: false,
    level: 2,
    rarity: "COMMON",
    traits: ["Bulwark"],
    category: "ARMOR",
    valueCp: 3000,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Heavy armor. +6 AC, Dex cap +0.",
  },
  {
    name: "Studded Leather Armor",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "ARMOR",
    valueCp: 300,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Light armor. +2 AC, Dex cap +3.",
  },
  {
    name: "Wooden Shield",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "ARMOR",
    valueCp: 100,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Shield. +2 AC, Hardness 3, HP 12, BT 6.",
  },
  {
    name: "Steel Shield",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "ARMOR",
    valueCp: 200,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Shield. +2 AC, Hardness 5, HP 20, BT 10.",
  },

  // ── Adventuring Gear ────────────────────────────────────
  {
    name: "Rope (50 ft)",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 100,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "50-foot length of rope. Climb DC 15.",
  },
  {
    name: "Grappling Hook",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 10,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Attach to a rope to anchor it.",
  },
  {
    name: "Adventurer's Pack",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 70,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Contains a backpack, bedroll, 10 pieces of chalk, flint and steel, 50 ft rope, 2 weeks rations, soap, 5 torches, and a waterskin.",
  },
  {
    name: "Bedroll",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 2,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "A portable sleeping roll.",
  },
  {
    name: "Flint and Steel",
    bulkValue: 0,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 5,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Used to start fires.",
  },
  {
    name: "Torch",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 1,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Provides bright light in 20-foot radius for 1 hour.",
  },
  {
    name: "Waterskin",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 5,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Holds water for 1 day.",
  },
  {
    name: "Rations (1 week)",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 40,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Preserved food for 1 week of travel.",
  },
  {
    name: "Thieves' Tools",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 300,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Required to pick locks or disable devices.",
  },
  {
    name: "Healer's Tools",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 500,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Required for Medicine checks to Treat Wounds.",
  },
  {
    name: "Alchemist's Tools",
    bulkValue: 2,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 300,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Required for Craft checks on alchemical items.",
  },
  {
    name: "Crowbar",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 50,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+1 item bonus to Athletics to Force Open.",
  },
  {
    name: "Tent (4-person)",
    bulkValue: 2,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 500,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Provides shelter for up to 4 people.",
  },
  {
    name: "Compass",
    bulkValue: 0,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 100,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+1 item bonus to Survival to Sense Direction.",
  },
  {
    name: "Lantern (Hooded)",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 70,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Bright light 30 ft radius, dim light 60 ft. Burns 6 hours per pint of oil.",
  },
  {
    name: "Oil (1 pint)",
    bulkValue: 0,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 1,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Fuel for lanterns. Burns for 6 hours.",
  },

  // ── Consumables ─────────────────────────────────────────
  {
    name: "Healing Potion (Minor)",
    bulkValue: 0,
    isBulkLight: true,
    level: 1,
    rarity: "COMMON",
    traits: ["Consumable", "Healing", "Magical", "Potion"],
    category: "CONSUMABLE",
    valueCp: 400,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Heals 1d8 HP.",
  },
  {
    name: "Healing Potion (Lesser)",
    bulkValue: 0,
    isBulkLight: true,
    level: 3,
    rarity: "COMMON",
    traits: ["Consumable", "Healing", "Magical", "Potion"],
    category: "CONSUMABLE",
    valueCp: 1200,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Heals 2d8+5 HP.",
  },
  {
    name: "Healing Potion (Moderate)",
    bulkValue: 0,
    isBulkLight: true,
    level: 6,
    rarity: "COMMON",
    traits: ["Consumable", "Healing", "Magical", "Potion"],
    category: "CONSUMABLE",
    valueCp: 5000,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Heals 3d8+10 HP.",
  },
  {
    name: "Antidote (Lesser)",
    bulkValue: 0,
    isBulkLight: true,
    level: 1,
    rarity: "COMMON",
    traits: ["Consumable", "Elixir", "Healing"],
    category: "CONSUMABLE",
    valueCp: 300,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+2 item bonus to Fortitude saves vs. poison for 6 hours.",
  },
  {
    name: "Antiplague (Lesser)",
    bulkValue: 0,
    isBulkLight: true,
    level: 1,
    rarity: "COMMON",
    traits: ["Consumable", "Elixir", "Healing"],
    category: "CONSUMABLE",
    valueCp: 300,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+2 item bonus to Fortitude saves vs. disease for 24 hours.",
  },
  {
    name: "Scroll of Heal (1st)",
    bulkValue: 0,
    isBulkLight: true,
    level: 1,
    rarity: "COMMON",
    traits: ["Consumable", "Magical", "Scroll"],
    category: "CONSUMABLE",
    valueCp: 400,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "One-use scroll. Casts Heal (1st level).",
  },
  {
    name: "Arrows (10)",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "CONSUMABLE",
    valueCp: 10,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "10 arrows for bows.",
  },
  {
    name: "Bolts (10)",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "CONSUMABLE",
    valueCp: 10,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "10 bolts for crossbows.",
  },

  // ── Magical / Investable Items ──────────────────────────
  {
    name: "Cloak of Resistance (+1)",
    bulkValue: 0,
    isBulkLight: true,
    level: 5,
    rarity: "COMMON",
    traits: ["Invested", "Magical", "Abjuration"],
    category: "WORN",
    valueCp: 16000,
    isInvestable: true,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+1 item bonus to all saving throws.",
  },
  {
    name: "Ring of Protection (+1)",
    bulkValue: 0,
    isBulkLight: false,
    level: 6,
    rarity: "COMMON",
    traits: ["Invested", "Magical", "Abjuration"],
    category: "WORN",
    valueCp: 24500,
    isInvestable: true,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+1 item bonus to AC.",
  },
  {
    name: "Aeon Stone (Dull Grey)",
    bulkValue: 0,
    isBulkLight: false,
    level: 1,
    rarity: "UNCOMMON",
    traits: ["Invested", "Magical", "Transmutation"],
    category: "WORN",
    valueCp: 900,
    isInvestable: true,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Orbits your head. No special abilities but can be etched with a wayfinder.",
  },
  {
    name: "Bracers of Armor (+1)",
    bulkValue: 0,
    isBulkLight: true,
    level: 4,
    rarity: "COMMON",
    traits: ["Invested", "Magical", "Abjuration"],
    category: "WORN",
    valueCp: 9000,
    isInvestable: true,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+1 item bonus to AC (for unarmored characters).",
  },

  // ── Kingmaker-relevant items ────────────────────────────
  {
    name: "Fishing Tackle",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 80,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Required for the Fishing camping activity.",
  },
  {
    name: "Cooking Kit",
    bulkValue: 2,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 100,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Required for the Cook Special Meal camping activity.",
  },
  {
    name: "Climber's Kit",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 50,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "+1 item bonus to Athletics to Climb.",
  },
  {
    name: "Writing Kit",
    bulkValue: 0,
    isBulkLight: true,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 100,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Ink, quills, and paper for taking notes.",
  },
  {
    name: "Repair Kit",
    bulkValue: 1,
    isBulkLight: false,
    level: 0,
    rarity: "COMMON",
    traits: [],
    category: "GEAR",
    valueCp: 200,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Required for Craft checks to Repair items.",
  },
  {
    name: "Cold Iron Blanch (Low-Grade)",
    bulkValue: 0,
    isBulkLight: true,
    level: 2,
    rarity: "COMMON",
    traits: ["Consumable", "Alchemical"],
    category: "CONSUMABLE",
    valueCp: 600,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Apply to a weapon. Next 3 Strikes count as cold iron.",
  },
  {
    name: "Silver Blanch (Low-Grade)",
    bulkValue: 0,
    isBulkLight: true,
    level: 2,
    rarity: "COMMON",
    traits: ["Consumable", "Alchemical"],
    category: "CONSUMABLE",
    valueCp: 600,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Apply to a weapon. Next 3 Strikes count as silver.",
  },
  {
    name: "Wand of Heal (1st level)",
    bulkValue: 0,
    isBulkLight: true,
    level: 3,
    rarity: "COMMON",
    traits: ["Magical", "Healing", "Necromancy", "Wand"],
    category: "WAND",
    valueCp: 6000,
    isInvestable: false,
    containerCapacity: null,
    containerBulkReduction: null,
    description: "Cast Heal (1st level) once per day.",
  },
];
